### ISSUE TITLE
A few suggested enhancements to help in getting started

### ISSUE THREAD

**Issue by disquisitioner** [ericklein/powered_air_quality#5]
As a way of getting familiar with PAQ and the CYD I attempted to start from scratch with a new dev board, no sensors, and an empty repo based just on cloning main.  My two part goal was to (1) get everything to compile and (2) to then get the program running in hardware simulation mode.  I was successful, but in the process found a few things that could enhance the documentation (README) and bits of the code:

1.  I think it'd be good to list in the README the library dependencies, which I discovered to be:
      *) ArduinoJson by Benoit Blanchon
      *) Adafruit ILI9341 (and dependencies)
      *) Sensirion I2C SEN5X (and dependencies)
      *) Sensirion I2C SCD4x (and dependencies)
      *) ESP8266 Influxdb by Tobias Schurg (which also works for ESP32 despite the name)

2. For the CYD the Arduino IDE should be told to target the "ESP32 Dev Module" board, which you can find once you install the ESP32 BCP

3.  The code presumes a few Open Weather Map configuration parameters are defined, presumably in `secrets.h`, but they're not included in `secrets_template.h`.  I'd suggest adding place holder examples for these in `secrets_template.h`:
      *) `OWM_LAT_LONG` (which needs to be in a special format, e.g. `"lat=44.34&lon=10.99"`)
      *) `OWM_KEY` (which people need to obtain by creating an account at https://openweathermap.org/)

4. By default InfluxDB services are enabled in `config.h` but probably shouldn't be to parallel the approach used for MQTT. This could be mentioned in the README as is the case now for MQTT.

I could submit a PR for these but would want to coordinate with work underway in the `dev `branch,  Perhaps I could do that after the work in the dev branch gets merged into main.

With the above, enabling HARDWARE_SIMULATE in config.h worked the first time, yielding a working instance of PAQ with no sensors attached but with reasonable simulated values.  NICE!!

**Comment by ericklein** [comment]
Suggested documentation changes and secret_template.h changes rolled into /dev and will be promoted to /main shortly.
